#!/usr/bin/env bash
# setup-aliases.sh - Auto-setup GLM aliases for system-wide access
# Usage: ./setup-aliases.sh [--install|--install-system|--check|--uninstall]
#
# P13: Setup script for shell aliases
# Expert panel: 13/13 unanimous approval
# Architecture: Source file in ~/.zshrc (simple and reliable)

set -euo pipefail

# =============================================================================
# Configuration
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ALIASES_FILE="$SCRIPT_DIR/glm-aliases.sh"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# =============================================================================
# Logging Functions
# =============================================================================

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1" >&2; }

# =============================================================================
# Prerequisites Check
# =============================================================================

check_prerequisites() {
    log_info "Checking prerequisites..."

    if [[ ! -f "$ALIASES_FILE" ]]; then
        log_error "Aliases file not found: $ALIASES_FILE"
        return 1
    fi

    if [[ ! -f "$PROJECT_ROOT/glm-launch.sh" ]]; then
        log_error "Launcher script not found: $PROJECT_ROOT/glm-launch.sh"
        return 1
    fi

    log_success "✅ Prerequisites check passed"
    return 0
}

# =============================================================================
# Shell Detection
# =============================================================================

detect_shell() {
    # P13: Use $SHELL environment variable (user's login shell)
    # This is more reliable than $ZSH_VERSION/$BASH_VERSION (which show subprocess)
    local user_shell="${SHELL:-}"

    if [[ -z "$user_shell" ]]; then
        # Fallback: check version variables
        if [[ -n "${ZSH_VERSION:-}" ]]; then
            echo "zsh"
        elif [[ -n "${BASH_VERSION:-}" ]]; then
            echo "bash"
        else
            echo "unknown"
        fi
        return 0
    fi

    # Extract shell name from path (e.g., /bin/zsh → zsh)
    local shell_name
    shell_name="$(basename "$user_shell")"

    case "$shell_name" in
        zsh)
            echo "zsh"
            ;;
        bash)
            echo "bash"
            ;;
        *)
            echo "unknown"
            ;;
    esac
}

# =============================================================================
# Installation Functions
# =============================================================================

# Add source block to ~/.zshrc
add_zsh_source() {
    local zshrc="$HOME/.zshrc"
    local source_block="
# GLM Aliases - Auto-generated by setup-aliases.sh
# Source glm aliases for Claude Code launcher
source \"$ALIASES_FILE\"
"

    # Check if source block already exists
    if grep -q "GLM Aliases - Auto-generated by setup-aliases.sh" "$zshrc" 2>/dev/null; then
        log_info "✅ Source already configured in ~/.zshrc"
        return 0
    fi

    # Backup .zshrc
    if [[ -f "$zshrc" ]]; then
        local backup="${zshrc}.bak.$(date +%s)"
        cp "$zshrc" "$backup"
        log_info "Backed up ~/.zshrc to $backup"
    fi

    # Append source block
    echo "" >> "$zshrc"
    echo "$source_block" >> "$zshrc"

    log_success "✅ Added source to ~/.zshrc"
    return 0
}

# Install for Zsh (source method)
install_zsh() {
    log_info "Installing for Zsh (source method)..."

    # Add source to ~/.zshrc
    add_zsh_source || return 1

    echo ""
    log_success "✅ Installation complete!"
    echo ""
    log_info "To enable aliases NOW, run:"
    log_info "  source ~/.zshrc"
    echo ""
    log_info "Or restart your shell:"
    log_info "  exec zsh"

    return 0
}

# Add source block to ~/.bashrc
add_bash_source() {
    local bashrc="$HOME/.bashrc"
    local source_block="
# GLM Aliases - Auto-generated by setup-aliases.sh
# Source glm aliases for Claude Code launcher
source \"$ALIASES_FILE\"
"

    # Check if source block already exists
    if grep -q "GLM Aliases - Auto-generated by setup-aliases.sh" "$bashrc" 2>/dev/null; then
        log_info "✅ Source already configured in ~/.bashrc"
        return 0
    fi

    # Backup .bashrc
    if [[ -f "$bashrc" ]]; then
        local backup="${bashrc}.bak.$(date +%s)"
        cp "$bashrc" "$backup"
        log_info "Backed up ~/.bashrc to $backup"
    fi

    # Append source block
    echo "" >> "$bashrc"
    echo "$source_block" >> "$bashrc"

    log_success "✅ Added source to ~/.bashrc"
    return 0
}

# Install for Bash (source method)
install_bash() {
    log_info "Installing for Bash (source method)..."

    # Add source to ~/.bashrc
    add_bash_source || return 1

    echo ""
    log_success "✅ Installation complete!"
    echo ""
    log_info "To enable aliases NOW, run:"
    log_info "  source ~/.bashrc"
    echo ""
    log_info "Or restart your shell:"
    log_info "  exec bash"

    return 0
}

# Install system-wide (profile.d)
install_system() {
    log_info "Installing system-wide (requires sudo)..."

    if [[ $EUID -ne 0 ]]; then
        log_error "This option requires sudo. Run: sudo ./setup-aliases.sh --install-system"
        return 1
    fi

    local target="/etc/profile.d/glm-aliases.sh"

    # Backup existing
    if [[ -f "$target" ]]; then
        local backup="${target}.bak.$(date +%s)"
        cp "$target" "$backup"
        log_info "Backed up existing $target to $backup"
    fi

    # Copy with project root substitution for robustness
    sed "s|%%PROJECT_ROOT%%|$PROJECT_ROOT|g" "$ALIASES_FILE" > "$target"
    chmod +x "$target"

    log_success "✅ Installed to $target"
    log_info ""
    log_info "Aliases will be available in new shell sessions for all users"

    return 0
}

# =============================================================================
# Status Check
# =============================================================================

check_installation() {
    log_info "Checking installation status..."

    local installed=false
    local shell=$(detect_shell)

    case "$shell" in
        zsh)
            if grep -q "GLM Aliases - Auto-generated by setup-aliases.sh" "$HOME/.zshrc" 2>/dev/null; then
                log_success "✅ Installed for Zsh (source in ~/.zshrc)"
                installed=true
            fi
            ;;
        bash)
            if grep -q "GLM Aliases - Auto-generated by setup-aliases.sh" "$HOME/.bashrc" 2>/dev/null; then
                log_success "✅ Installed for Bash (source in ~/.bashrc)"
                installed=true
            fi
            ;;
    esac

    if [[ -f "/etc/profile.d/glm-aliases.sh" ]]; then
        log_success "✅ Installed system-wide (profile.d)"
        installed=true
    fi

    if [[ "$installed" == "false" ]]; then
        log_warning "❌ Not installed"
        log_info "Run: ./scripts/setup-aliases.sh --install"
    fi

    return 0
}

# =============================================================================
# Uninstall Functions
# =============================================================================

# Remove source from ~/.zshrc
remove_zsh_source() {
    local zshrc="$HOME/.zshrc"

    # Check if source block exists
    if ! grep -q "GLM Aliases - Auto-generated by setup-aliases.sh" "$zshrc" 2>/dev/null; then
        log_info "ℹ️  No source block found in ~/.zshrc"
        return 0
    fi

    # Backup .zshrc
    local backup="${zshrc}.bak.$(date +%s)"
    cp "$zshrc" "$backup"
    log_info "Backed up ~/.zshrc to $backup"

    # Remove source block (from marker to end of GLM block)
    local temp_file=$(mktemp)
    awk '
    /^# GLM Aliases - Auto-generated by setup-aliases.sh/ { skip = 1; next }
    skip && /^$/ { skip = 0; next }
    !skip { print }
    ' "$zshrc" > "$temp_file"

    mv "$temp_file" "$zshrc"

    log_success "✅ Removed source from ~/.zshrc"
    return 0
}

# Uninstall Zsh
uninstall_zsh() {
    log_info "Uninstalling GLM aliases for Zsh..."

    # Remove source from ~/.zshrc
    remove_zsh_source

    log_success "✅ Uninstall complete!"
    log_info "Restart your shell to apply changes: exec zsh"
    return 0
}

# Uninstall Bash
uninstall_bash() {
    log_info "Uninstalling GLM aliases for Bash..."

    local bashrc="$HOME/.bashrc"

    # Check if source block exists
    if ! grep -q "GLM Aliases - Auto-generated by setup-aliases.sh" "$bashrc" 2>/dev/null; then
        log_info "ℹ️  No source block found in ~/.bashrc"
        return 0
    fi

    # Backup .bashrc
    local backup="${bashrc}.bak.$(date +%s)"
    cp "$bashrc" "$backup"
    log_info "Backed up ~/.bashrc to $backup"

    # Remove source block
    local temp_file=$(mktemp)
    awk '
    /^# GLM Aliases - Auto-generated by setup-aliases.sh/ { skip = 1; next }
    skip && /^$/ { skip = 0; next }
    !skip { print }
    ' "$bashrc" > "$temp_file"

    mv "$temp_file" "$bashrc"

    log_success "✅ Removed source from ~/.bashrc"
    log_success "✅ Uninstall complete!"
    log_info "Restart your shell to apply changes: exec bash"
    return 0
}

# =============================================================================
# Main Function
# =============================================================================

main() {
    # Check prerequisites first
    check_prerequisites || exit 1

    local action="${1:---install}"
    local shell=$(detect_shell)

    log_info "Detected shell: $shell"
    log_info "Project root: $PROJECT_ROOT"
    log_info "Aliases file: $ALIASES_FILE"
    echo ""

    case "$action" in
        --install)
            case "$shell" in
                zsh)
                    install_zsh
                    ;;
                bash)
                    install_bash
                    ;;
                *)
                    log_error "Unknown shell: $shell"
                    log_info ""
                    log_info "Manual installation:"
                    log_info "  Add to your shell config (~/.zshrc or ~/.bashrc):"
                    log_info "  source $ALIASES_FILE"
                    exit 1
                    ;;
            esac
            ;;
        --install-system)
            install_system
            ;;
        --check)
            check_installation
            ;;
        --uninstall)
            case "$shell" in
                zsh)
                    uninstall_zsh
                    ;;
                bash)
                    uninstall_bash
                    ;;
                *)
                    log_error "Unknown shell: $shell"
                    exit 1
                    ;;
            esac
            ;;
        *)
            log_error "Unknown action: $action"
            log_info ""
            log_info "Usage: $0 [--install|--install-system|--check|--uninstall]"
            log_info ""
            log_info "Options:"
            log_info "  --install         Auto-install for current shell (zsh/bash)"
            log_info "  --install-system  Install system-wide (requires sudo)"
            log_info "  --check            Check installation status"
            log_info "  --uninstall        Uninstall aliases"
            exit 1
            ;;
    esac
}

# Run main if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
